# Sonoff S31 Relay Switch Template
#
# *...*
#
# SEE ALSO
# 1.
#
---

# 1. curl -v -X POST \
#  "http://<ip>/switch/switch_relay/toggle" \
# --digest -u <username>:<password>
# web_server username and password
switch:
  - platform: gpio
    name: "Relay"
    pin: GPIO12
    id: relay_switch
    restore_mode: RESTORE_DEFAULT_ON
    # IMPORTANT(JEFF): Powering the relay may cause damage or instability when the programmer is supplying Vcc.
    #restore_mode: ALWAYS_OFF

