# Sonoff S31 Smart WiFi Plug
#
# SEE ALSO
# 1. https://devices.esphome.io/devices/Sonoff-S31
# 2. curl -X POST http://sonoff-s31-5.ha.home/switch/relay/turn_on
# 3. curl -X POST http://sonoff-s31-5.ha.home/switch/relay/turn_off
#
# [1]: IMPORTANT(JEFF): Avoid the potential scenario where lack 
# of comms with this component invokes an automatic restart of 
# the device node. This is by design and is intended to act as
# an aid in automatic comms "healing".
#
# This particular smart plug serves a mission critical purpose
# and is presently immune to the above "patching" only because
# of the relay switch's restore_mode attribute being always on.
# If this were to change inadvertedly, this patch is the only
# other failsafe to not bringing our home Internet connection 
# down every 15 minutes or so...
---

esphome:
  name: "sonoff-s31-5"
  friendly_name: "carpnet-relay-1"
  area: "Kids Bedroom"

esp8266:
  early_pin_init: false

# OTA (Over The Air) updates without physical console
ota:
  - platform: esphome
    #password: !secret ota_password
    password: "a2d142f00ae9c74a444aa61cbd8d74d9"

api:
  # See [IMPORTANT][1] note
  reboot_timeout: 0s
  encryption:
    key: !secret api5_key

packages:
  #ota: !include configs/ota.yml
  #sonoff_relay_switch: !include configs/sonoff-s31/relay_switch.yml
  esp8266_platform: !include configs/esp8266/esp12/platform.yml
  esp8266_storage: !include configs/esp8266/flash_storage.yml
  logger_sonoff: !include configs/sonoff-s31/logger.yml
  sensor_wifi_signal: !include configs/sensor/wifi_signal.yml
  sonoff_gpios: !include configs/sonoff-s31/gpios.yml
  sonoff_project: !include configs/sonoff-s31/project.yml
  sonoff_uart: !include configs/sonoff-s31/uart.yml
  switch_factory_reset: !include configs/switch/factory_reset.yml
  switch_restart: !include configs/switch/restart.yml
  webserver: !include configs/webserver.yml
  wifi: !include configs/wifi.yml

<<: !include configs/development.yml
#<<: !include configs/production.yml

wifi:
  output_power: 15.00
  # See [IMPORTANT][1] note
  reboot_timeout: 0s

mqtt:
  # See [IMPORTANT][1] note
  reboot_timeout: 0s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Status"

sensor:
  - platform: cse7766
    current:
      name: "Current"
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s
    voltage:
      name: "Voltage"
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s
    power:
      name: "Power"
      accuracy_decimals: 2
      id: my_power
      filters:
        - throttle_average: 60s
    energy:
      name: "Energy"
      accuracy_decimals: 2
      filters:
        - throttle: 60s
    apparent_power: #(only available with version 2024.3.0 or greater)
      name: "Apparent Power"
      filters:
        - throttle_average: 60s
    power_factor: #(only available with version 2024.3.0 or greater)
      name: "Power Factor"
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s

  - platform: total_daily_energy #(Optional, not specific to cse7766)
    name: "Daily Energy"
    power_id: my_power
    accuracy_decimals: 2

switch:
  - platform: gpio
    name: "Relay"
    pin: GPIO12
    id: relay
    # restore_mode: ALWAYS_OFF # Powering the relay may cause damage or instability when the programmer is supplying Vcc.
    restore_mode: RESTORE_DEFAULT_ON

