# Generic ESP8266 Deep Sleep Template
#
# ...
#
# SEE ALSO
# 1. https://esphome.io/components/deep_sleep#
# 2.
# 3.
# 4.
---

deep_sleep:
  id: deep_sleep_esp8266
  run_duration: 3min
  sleep_duration: 27min
