esphome:
  name: s31
  friendly_name: s31

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Wsocd+hJNRzNTuYCO/8BvSBTbT9+I6DlgcvlwGXOeQs="

ota:
  - platform: esphome
    password: "cd210fea73443be326bec51bd301d683"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "S31 Fallback Hotspot"
    password: "lXjPfys3x5Nw"

captive_portal:
    