# WiFi component defaults
#
# https://esphome.io/components/wifi.html
---

wifi:
  id: wifi_conn
  # TODO(JEFF): Relocate power_save_mode (none) to esp8266 
  # specific settings && set power_save_mode to light for
  # ESP32
  power_save_mode: none # default for ESP8266
  domain: .ha.home
  # WARNING(JEFF): This value is likely to require further tweaks before
  # we can truly trust it as a default value!
  #output_power: 15.00
  fast_connect: false
  networks:
    # syn_2g; primary AP
    - ssid: !secret wifi_ssid0
      password: !secret wifi_ssid0_password
      priority: 100
    # NETGEAR11; failsafe backup AP
    #- ssid: !secret wifi_ssid1
      #password: !secret wifi_ssid1_password
      #priority: 10
  # Enable fallback hotspot in case of emergency
  ap:
    ssid: "${lower_devicename}_Hotspot"
    password: "UOR6GLP0CBdi"

captive_portal:

