# ESP8266 status LED heartbeat template
#
# SEE ALSO
# 1. https://esphome.io/components/light/status_led
# 2. https://esphome.io/components/light/binary
# 3. https://esphome.io/guides/configuration-types.html
#
---

# Toggle switch for status LED
light:
  - platform: status_led
    name: blue_led
    # LED_BUILTIN
    pin:
      number: GPIO2
      inverted: True
      # TODO(JEFF): I am not yet certain that this should be done;
      # we must verify that this is the correct use.
      #allow_other_uses: true
    restore_mode: RESTORE_DEFAULT_ON
