# Generic ESP8266 ESP12 Platform for ESPHome
#
# SEE ALSO
# 1.
#
---

esp8266:
  # https://i0.wp.com/randomnerdtutorials.com/wp-content/uploads/2019/05/ESP8266-ESP-12E-chip-pinout-gpio-pin.png?quality=100&strip=all&ssl=1
  board: esp12e
