# WiFi component defaults
#
# https://esphome.io/components/wifi.html
---

wifi:
  id: esp8266_wifi_conn
  power_save_mode: none # default for ESP8266
  domain: .ha.home
  fast_connect: false
  networks:
    # syn_2g; primary AP
    - ssid: !secret wifi_ssid0
      password: !secret wifi_ssid0_password
      priority: 100
    # NETGEAR11; failsafe backup AP
    #- ssid: !secret wifi_ssid1
      #password: !secret wifi_ssid1_password
      #priority: 10
  # Enable fallback hotspot in case of emergency
  ap:
    ssid: "${lower_devicename}_Hotspot"
    password: "UOR6GLP0CBdi"

captive_portal:

